width: 4.0
height: 4.0
resolution: 0.03

plugins:
 - {name: social_proxemics,  type: "social_navigation_layers::ProxemicLayer",  output: "screen"}
 - {name: social_passing,  type: "social_navigation_layers::PassingLayer",  output: "screen"}
 - {name: obstacles,  type: "costmap_2d::VoxelLayer"}
 - {name: inflater,  type: "costmap_2d::InflationLayer"}
publish_frequency: 2.0
