width: 10.0
height: 10.0
resolution: 0.05
origin_x: 0.0
origin_y: 0.0

plugins:
# - {name: static_map, type: "costmap_2d::StaticLayer"}
 - {name: obstacles,  type: "costmap_2d::FetchDepthLayer"}
 - {name: inflater,   type: "costmap_2d::InflationLayer"}
